export const WASTE_CATEGORY_DETAILS = 'WASTE_CATEGORY_DETAILS';
export const WASTE_CATEGORY_DETAIL = 'WASTE_CATEGORY_DETAIL';

export const WASTE_DETAILS = 'WASTE_DETAILS';
export const WASTE_DETAIL = 'WASTE_DETAIL';
